"""
Approval Module for AutoResolve.

Handles PR creation, approval workflow, and maintainer notifications.
"""

import asyncio
import logging
import os
import re
import subprocess
import tempfile
from datetime import datetime, timedelta, timezone
from typing import Optional
from uuid import uuid4

from app.config import get_settings
from models.schemas import (
    ApprovalResult,
    FixProposal,
    PullRequestResult,
    SecurityReport,
)

logger = logging.getLogger(__name__)

# Comment templates
APPROVAL_COMMENT_TEMPLATE = """## AutoResolve Analysis Complete

| Check | Status |
|-------|--------|
| **Reproduction** | {reproduction_status} |
| **Fix Generated** | {fix_status} |
| **Security Scan** | {security_status} |

### Proposed Fix

<details>
<summary>Click to view diff ({lines_changed} lines changed)</summary>

```diff
{diff}
```

</details>

### Security Report

{security_summary}

---

### Actions

| Command | Description |
|---------|-------------|
| `@autoresolve approve` | Create PR and merge |
| `@autoresolve approve --no-merge` | Create PR only |
| `@autoresolve reject` | Decline this fix |
| `@autoresolve regenerate` | Generate a new fix |

**Expires:** {expiry_date} ({days_remaining} days)

---
<sub>AutoResolve v{version} | [Documentation](https://github.com/yourorg/autoresolve)</sub>
"""

PR_BODY_TEMPLATE = """## Summary

Automated fix for #{issue_number}: {issue_title}

## Changes

{diff_summary}

## Validation

- Reproduction: {reproduction_status}
- Patch applies cleanly: {patch_status}
- Syntax validation: {syntax_status}
- Security scan: {security_status}

## Security Scan Results

| Severity | Count |
|----------|-------|
| Critical | {critical} |
| High | {high} |
| Medium | {medium} |
| Low | {low} |

## Approval

Approved by @{approved_by} on {approved_at}

---

<sub>Generated by [AutoResolve](https://github.com/yourorg/autoresolve) v{version}</sub>

Closes #{issue_number}
"""


def format_security_summary(report: SecurityReport) -> str:
    """Format security report for comment display with actionable details."""
    if not report.has_vulnerabilities:
        return "No security issues detected"

    from modules.security_auditor import OWASP_REFERENCES

    lines = [f"**Risk Score:** {report.risk_score:.2f}"]
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")

    for severity in ["critical", "high", "medium", "low", "info"]:
        count = report.findings_by_severity.get(severity, 0)
        if count > 0:
            lines.append(f"| {severity.title()} | {count} |")

    if report.critical_findings:
        lines.append("")
        lines.append("**Critical/High Findings:**")
        for finding in report.critical_findings[:5]:
            cwe_tag = f" [{finding.cwe}]" if finding.cwe else ""
            lines.append(
                f"- **{finding.file}:{finding.line_start}**{cwe_tag} — {finding.message}"
            )
            if finding.recommendation:
                lines.append(f"  - Fix: {finding.recommendation}")
            if finding.cwe and finding.cwe in OWASP_REFERENCES:
                lines.append(
                    f"  - Ref: {OWASP_REFERENCES[finding.cwe]}"
                )

    return "\n".join(lines)


async def post_proposal_comment(
    repo_full_name: str,
    issue_number: int,
    proposal: FixProposal,
    security_report: SecurityReport,
    reproduction_valid: bool,
) -> int:
    """
    Post a comment to the GitHub issue with the fix proposal.

    Args:
        repo_full_name: Repository full name (org/repo)
        issue_number: GitHub issue number
        proposal: Fix proposal
        security_report: Security audit report
        reproduction_valid: Whether issue was reproduced

    Returns:
        Comment ID
    """
    settings = get_settings()

    # Format comment
    lines_changed = proposal.lines_added + proposal.lines_removed
    expiry_date = (
        datetime.now(timezone.utc) + timedelta(days=settings.approval.timeout_days)
    ).strftime("%Y-%m-%d")

    comment_body = APPROVAL_COMMENT_TEMPLATE.format(
        reproduction_status="Confirmed" if reproduction_valid else "Partial",
        fix_status="Available",
        security_status=f"{'Passed' if security_report.recommendation == 'approve' else 'Review Required'} ({security_report.findings_count} findings)",
        lines_changed=lines_changed,
        diff=proposal.suggested_patch[:5000],  # Truncate long diffs
        security_summary=format_security_summary(security_report),
        expiry_date=expiry_date,
        days_remaining=settings.approval.timeout_days,
        version=settings.app.version,
    )

    # Post comment via GitHub API with proper resource cleanup
    from services.github_service import GitHubService

    async with GitHubService() as github:
        comment_id = await github.create_issue_comment(
            repo=repo_full_name, issue_number=issue_number, body=comment_body
        )

    logger.info(
        f"Posted proposal comment to {repo_full_name}#{issue_number}: {comment_id}"
    )

    return comment_id


async def poll_for_approval(
    repo_full_name: str, issue_number: int, proposal: FixProposal
) -> ApprovalResult:
    """
    Check for maintainer approval response.

    Args:
        repo_full_name: Repository full name
        issue_number: GitHub issue number
        proposal: Fix proposal

    Returns:
        Approval result
    """
    settings = get_settings()
    max_retries = 3

    from services.github_service import GitHubService

    async with GitHubService() as github:
        # Get comments since proposal was posted with retry logic
        comments = []
        for attempt in range(max_retries):
            try:
                comments = await github.get_issue_comments(
                    repo=repo_full_name, issue_number=issue_number, since=proposal.generated_at
                )
                break
            except Exception as e:
                logger.warning(
                    f"Failed to get issue comments (attempt {attempt + 1}/{max_retries}): {e}"
                )
                if attempt < max_retries - 1:
                    await asyncio.sleep(2 ** attempt)  # Exponential backoff
                else:
                    logger.error(
                        f"All retries exhausted getting comments for {repo_full_name}#{issue_number}"
                    )
                    # Return pending status to retry on next poll cycle
                    return ApprovalResult(status="pending")

        # Get reactions on issue with retry logic
        reactions = []
        for attempt in range(max_retries):
            try:
                reactions = await github.get_issue_reactions(
                    repo=repo_full_name, issue_number=issue_number
                )
                break
            except Exception as e:
                logger.warning(
                    f"Failed to get issue reactions (attempt {attempt + 1}/{max_retries}): {e}"
                )
                if attempt < max_retries - 1:
                    await asyncio.sleep(2 ** attempt)  # Exponential backoff
                else:
                    logger.error(
                        f"All retries exhausted getting reactions for {repo_full_name}#{issue_number}"
                    )
                    # Continue without reactions - comments already retrieved

        # Check for approval commands in comments
        for comment in comments:
            author = comment.get("user", {}).get("login", "")

            # Only accept from maintainers
            try:
                is_maintainer = await github.is_maintainer(repo_full_name, author)
            except Exception as e:
                logger.warning(f"Failed to check maintainer status for {author}: {e}")
                continue

            if not is_maintainer:
                continue

            text = comment.get("body", "").lower()

            if "@autoresolve approve" in text:
                no_merge = "--no-merge" in text
                return ApprovalResult(
                    status="approved",
                    approved_by=author,
                    auto_merge=not no_merge,
                    resolved_at=datetime.now(timezone.utc),
                )

            if "@autoresolve reject" in text:
                reason = _extract_reason(comment.get("body", ""))
                return ApprovalResult(
                    status="rejected",
                    rejected_by=author,
                    rejection_reason=reason,
                    resolved_at=datetime.now(timezone.utc),
                )

            if "@autoresolve regenerate" in text:
                feedback = _extract_feedback(comment.get("body", ""))
                return ApprovalResult(status="regenerate", feedback=feedback)

        # Check reactions from maintainers
        for reaction in reactions:
            user = reaction.get("user", {}).get("login", "")
            content = reaction.get("content", "")

            try:
                is_maintainer = await github.is_maintainer(repo_full_name, user)
            except Exception as e:
                logger.warning(f"Failed to check maintainer status for {user}: {e}")
                continue

            if is_maintainer:
                if content == "+1":
                    return ApprovalResult(
                        status="approved",
                        approved_by=user,
                        auto_merge=True,
                        resolved_at=datetime.now(timezone.utc),
                    )
                if content == "-1":
                    return ApprovalResult(
                        status="rejected", rejected_by=user, resolved_at=datetime.now(timezone.utc)
                    )

        # Check expiry - handle both naive and aware datetimes
        now = datetime.now(timezone.utc)
        proposal_time = proposal.generated_at
        if proposal_time.tzinfo is None:
            proposal_time = proposal_time.replace(tzinfo=timezone.utc)

        if now > proposal_time + timedelta(days=settings.approval.timeout_days):
            return ApprovalResult(status="expired")

        return ApprovalResult(status="pending")


def _extract_reason(text: str) -> Optional[str]:
    """Extract rejection reason from comment."""
    # Look for text after "reject" command
    match = re.search(
        r"@autoresolve\s+reject\s*[:\-]?\s*(.+)", text, re.IGNORECASE | re.DOTALL
    )
    if match:
        reason = match.group(1).strip()
        # Stop at common delimiters
        for delim in ["\n\n", "---", "```"]:
            if delim in reason:
                reason = reason.split(delim)[0]
        return reason[:500] if reason else None
    return None


def _extract_feedback(text: str) -> Optional[str]:
    """Extract regeneration feedback from comment."""
    match = re.search(
        r"@autoresolve\s+regenerate\s*[:\-]?\s*(.+)", text, re.IGNORECASE | re.DOTALL
    )
    if match:
        feedback = match.group(1).strip()
        for delim in ["\n\n", "---", "```"]:
            if delim in feedback:
                feedback = feedback.split(delim)[0]
        return feedback[:500] if feedback else None
    return None


async def create_pull_request(
    proposal: FixProposal, approval: ApprovalResult, issue_title: str
) -> PullRequestResult:
    """
    Create a PR with the approved patch.

    Args:
        proposal: Approved fix proposal
        approval: Approval result
        issue_title: Original issue title

    Returns:
        Pull request result
    """
    settings = get_settings()

    from services.github_service import GitHubService

    # Use async context manager for proper resource cleanup
    async with GitHubService() as github:
        repo = proposal.repo_full_name
        base_branch = await github.get_default_branch(repo)

        # Create branch
        short_id = str(uuid4())[:8]
        branch_name = f"{settings.approval.branch_prefix}{proposal.issue_id}-{short_id}"

        await github.create_branch(repo=repo, branch=branch_name, from_ref=base_branch)

        # Apply patch via commits
        for file_diff in proposal.parsed_diff.files if proposal.parsed_diff else []:
            try:
                current_content = await github.get_file_contents(
                    repo, file_diff.path, base_branch
                )
                new_content = _apply_diff_to_content(
                    current_content, proposal.suggested_patch, file_diff.path
                )

                await github.update_file(
                    repo=repo,
                    path=file_diff.path,
                    content=new_content,
                    branch=branch_name,
                    message=f"fix: resolve issue #{proposal.issue_id}\n\nAutomated fix by AutoResolve",
                )
            except Exception as e:
                logger.error(f"Failed to update file {file_diff.path}: {e}")
                raise

        # Create PR
        pr_title = f"fix: {issue_title} (#{proposal.issue_id})"
        pr_body = PR_BODY_TEMPLATE.format(
            issue_number=proposal.issue_id,
            issue_title=issue_title,
            diff_summary=f"Changed {len(proposal.affected_files)} file(s), +{proposal.lines_added}/-{proposal.lines_removed} lines",
            reproduction_status="Confirmed",
            patch_status="Passed",
            syntax_status="Passed",
            security_status="Passed",
            critical=0,
            high=0,
            medium=0,
            low=0,
            approved_by=approval.approved_by or "system",
            approved_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            version=settings.app.version,
        )

        pr = await github.create_pull_request(
            repo=repo,
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=base_branch,
            labels=settings.approval.pr_labels,
        )

        pr_number = pr.get("number", 0)
        pr_url = pr.get("html_url", "")

        # Post link comment on issue
        await github.create_issue_comment(
            repo=repo,
            issue_number=proposal.issue_id,
            body=f"Pull request created: #{pr_number}",
        )

        logger.info(f"Created PR #{pr_number} for issue #{proposal.issue_id}")

        # Auto-merge if requested and allowed
        if approval.auto_merge and settings.approval.auto_merge_enabled:
            try:
                # Wait for checks if configured
                if settings.approval.auto_merge_wait_for_checks:
                    checks_passed = await _wait_for_checks(
                        github, repo, pr_number,
                        timeout=settings.approval.ci_checks_timeout_seconds
                    )
                    if not checks_passed:
                        await github.create_pr_comment(
                            repo=repo,
                            pr_number=pr_number,
                            body="Auto-merge skipped: CI checks failed",
                        )
                        return PullRequestResult(
                            pr_number=pr_number,
                            pr_url=pr_url,
                            branch_name=branch_name,
                            status="open",
                            checks_passed=False,
                        )

                # Merge the PR
                await github.merge_pull_request(
                    repo=repo,
                    pr_number=pr_number,
                    merge_method=settings.approval.auto_merge_method,
                )

                # Close the issue
                if settings.approval.close_issue_on_merge:
                    await github.close_issue(repo, proposal.issue_id)

                return PullRequestResult(
                    pr_number=pr_number,
                    pr_url=pr_url,
                    branch_name=branch_name,
                    status="merged",
                    checks_passed=True,
                    merged_at=datetime.now(timezone.utc),
                    merged_by="autoresolve",
                )

            except Exception as e:
                logger.error(f"Auto-merge failed: {e}")
                await github.create_pr_comment(
                    repo=repo, pr_number=pr_number, body=f"Auto-merge failed: {e}"
                )

        return PullRequestResult(
            pr_number=pr_number, pr_url=pr_url, branch_name=branch_name, status="open"
        )


def _apply_diff_to_content(content: str, diff: str, file_path: str) -> str:
    """Apply a unified diff to file content.

    Recreates the directory structure inside a temp dir so patches
    with subdirectory paths (e.g. auth/login.py) apply correctly.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        # Sanitize: strip traversal components, normalize
        sanitized = file_path.replace("..", "").lstrip("/\\")
        sanitized = os.path.normpath(sanitized)
        if not sanitized or sanitized == ".":
            sanitized = "patched_file.py"

        # Build full path inside tmpdir, creating parent dirs
        file_full_path = os.path.join(tmpdir, sanitized)
        resolved_path = os.path.realpath(file_full_path)
        if not resolved_path.startswith(os.path.realpath(tmpdir)):
            raise ValueError(f"Invalid file path: {file_path}")

        os.makedirs(os.path.dirname(file_full_path), exist_ok=True)

        with open(file_full_path, "w") as f:
            f.write(content)

        # Apply patch with -p1 (strips leading a/ or b/)
        result = subprocess.run(
            ["patch", "-p1", "-i", "-"],
            input=diff.encode(),
            cwd=tmpdir,
            capture_output=True,
        )

        if result.returncode != 0:
            # Try with -p0
            result = subprocess.run(
                ["patch", "-p0", "-i", "-"],
                input=diff.encode(),
                cwd=tmpdir,
                capture_output=True,
            )

        # Read patched content
        with open(file_full_path) as f:
            return f.read()


async def _wait_for_checks(
    github, repo: str, pr_number: int, timeout: int = 300
) -> bool:
    """Wait for CI checks to complete."""
    elapsed = 0
    interval = 15

    while elapsed < timeout:
        status = await github.get_pr_check_status(repo, pr_number)

        if status == "success":
            return True
        elif status == "failure":
            return False
        elif status == "pending":
            await asyncio.sleep(interval)
            elapsed += interval
        else:
            # No checks or unknown status
            return True

    logger.warning(f"Check status timeout for PR #{pr_number}")
    return False


async def handle_rejection(proposal: FixProposal, approval: ApprovalResult) -> None:
    """
    Handle a rejected proposal.

    Args:
        proposal: The rejected proposal
        approval: Rejection result
    """
    from models.database import AuditLog
    from models.database import FixProposal as DBFixProposal
    from models.database import get_db_session

    with get_db_session() as db:
        # Update proposal status
        db_proposal = (
            db.query(DBFixProposal)
            .filter(DBFixProposal.proposal_id == proposal.proposal_id)
            .first()
        )

        if db_proposal:
            db_proposal.status = "rejected"

        # Log rejection
        log = AuditLog(
            event_type="proposal.rejected",
            entity_type="proposal",
            entity_id=db_proposal.id if db_proposal else None,
            actor=approval.rejected_by,
            details={
                "reason": approval.rejection_reason,
                "proposal_id": str(proposal.proposal_id),
            },
        )
        db.add(log)

    logger.info(
        f"Proposal {proposal.proposal_id} rejected by {approval.rejected_by}"
    )


async def handle_expiry(proposal: FixProposal) -> None:
    """
    Handle an expired proposal.

    Args:
        proposal: The expired proposal
    """
    settings = get_settings()

    from services.github_service import GitHubService

    # Use async context manager for proper resource cleanup
    async with GitHubService() as github:
        # Post expiry notice
        await github.create_issue_comment(
            repo=proposal.repo_full_name,
            issue_number=proposal.issue_id,
            body=f"The fix proposal has expired after {settings.approval.timeout_days} days without a response. "
            f"If you would like to receive a new proposal, please reopen this issue or add the 'bug' label.",
        )

    # Update database
    from models.database import FixProposal as DBFixProposal
    from models.database import get_db_session

    with get_db_session() as db:
        db_proposal = (
            db.query(DBFixProposal)
            .filter(DBFixProposal.proposal_id == proposal.proposal_id)
            .first()
        )

        if db_proposal:
            db_proposal.status = "expired"

    logger.info(f"Proposal {proposal.proposal_id} expired")


